spring:
  application:
    name: Desafio-Futebol
  jpa:
    show-sql: true
    properties:
      hibernate:
        use-new-id-generator-mappings: false

gpt:
  secretKey:
  url:

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
